apiVersion: v1
kind: ConfigMap
metadata:
  name: basicauth1
  namespace: monitoring
data:
    htpasswd: |
      itrack:$apr1$z1drju5g$ZrAOUGTewgV1frLkT5KJG/

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceproxy-conf1
  namespace: monitoring
data:
  serviceproxy.conf: |
      server {
          listen       80;
          #server_name  _;
          location / {
              root   html;
              auth_basic "Private Property";
              auth_basic_user_file /etc/serviceproxy/htpasswd;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $host;
              index  index.html index.htm;
              proxy_pass http://11.23.43.45:9093/;       #alert-manager svc ip
          }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceproxy1
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: serviceproxy1
  template:
    metadata:
      labels:
        app: serviceproxy1
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
        - name: htpasswd
          mountPath: /etc/serviceproxy/
      volumes:
      - name: config-volume
        configMap:
          name: serviceproxy-conf1
          items:
          - key: serviceproxy.conf
            path: serviceproxy.conf
      - name: htpasswd
        configMap:
          name: basicauth1
          items:
          - key: htpasswd
            path: htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc1
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
     - port: 80
       targetPort: 80
  selector:
          app: serviceproxy1
